config:
  project_name: hyperparam_opt_grub
  run_name: fnn_testrun
  nn_arch: simple_fnn
  b_size: 256
  n_hlay: 0
  hdim: 128
  lr: 0.002962942736441659
  act_fn: tanh
  loss_fn: mae
  opt: adam
  metric: val/loss
  mode: min
  logmetric1_name: u_accuracy
  logmetric2_name: v_accuracy
  n_inputs: 12
  n_outputs: 8
  accuracy_tolerance: 0.01
  num_workers: 6
  generate_new_data: false
  learn_mode: x
  dataset_size: 120000
  normalized_data: true
  dt: 0.01
  cpu_num: 7
  gpu_num: 1.0
  max_epochs: 750
  num_samples: 200
  path: /home/daniel/research/catkin_ws/src/hyperparam_optimization/bellows_grub/
