config:
  project_name: hyperparam_opt_grub
  run_name: fnn_lhs_final
  nn_arch: simple_fnn
  b_size: 16
  n_hlay: 0
  hdim: 64
  lr: 0.007877548421243002
  act_fn: sigmoid
  loss_fn: mse
  metric: val/loss
  mode: min
  logmetric1_name: u_accuracy
  logmetric2_name: v_accuracy
  opt: adam
  n_inputs: 12
  n_outputs: 8
  accuracy_tolerance: 0.01
  num_workers: 6
  generate_new_data: false
  learn_mode: x
  dataset_size: 100000
  normalized_data: true
  sampling_method: lhs
  dt: 0.01
  cpu_num: 7
  gpu_num: 1.0
  max_epochs: 750
  num_samples: 150
  path: /home/daniel/research/catkin_ws/src/hyperparam_optimization/bellows_grub/
