wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1683169115.10994
    t:
      1:
      - 30
      - 55
      2:
      - 30
      - 55
      3:
      - 2
      - 13
      - 14
      - 16
      - 19
      - 23
      4: 3.8.10
      5: 0.14.0
      8:
      - 8
accuracy_tolerance:
  desc: null
  value: 0.01
act_fn:
  desc: null
  value: relu
b_size:
  desc: null
  value: 16
calculates_xdot:
  desc: null
  value: false
cpu_num:
  desc: null
  value: 3
dataset_size:
  desc: null
  value: 60000
date:
  desc: null
  value: 2023-05-03_23-33-23
dt:
  desc: null
  value: 0.01
experiment_id:
  desc: null
  value: 4ced51bd198c4a1eb77e303ee74cd5b8
generate_new_data:
  desc: null
  value: true
gpu_num:
  desc: null
  value: 0.4
hdim:
  desc: null
  value: 512
hostname:
  desc: null
  value: CTB455-Salmon
learn_mode:
  desc: null
  value: x
loss_fn:
  desc: null
  value: mse
lr:
  desc: null
  value: 0.0004008999886407782
max_epochs:
  desc: null
  value: 500
n_hlay:
  desc: null
  value: 0
n_inputs:
  desc: null
  value: 3
n_outputs:
  desc: null
  value: 2
nn_arch:
  desc: null
  value: simple_fnn
node_ip:
  desc: null
  value: 10.32.114.243
normalized_data:
  desc: null
  value: false
num_samples:
  desc: null
  value: 200
num_workers:
  desc: null
  value: 6
opt:
  desc: null
  value: adam
path:
  desc: null
  value: /home/daniel/research/catkin_ws/src/hyperparam_optimization/inverted_pendulum/
pid:
  desc: null
  value: 827447
project_name:
  desc: null
  value: hyperparam_opt_ip
run_name:
  desc: null
  value: fnn_optimization
trial_id:
  desc: null
  value: 21f01584
trial_log_path:
  desc: null
  value: /home/daniel/research/catkin_ws/src/hyperparam_optimization/inverted_pendulum/run_logs/fnn_optimization/train_21f01584_85_accuracy_tolerance=0.0100,act_fn=relu,b_size=16,calculates_xdot=False,cpu_num=3,dataset_size=60000,dt=0.0100,gen_2023-05-03_20-58-32
